### PR TITLE
Upgrade update.. still some review required

### PR DESCRIPTION
**Pull request by viveky259259**
some changes to library versions
and some dart upgrade changes

** Not able to run in my machine

### CODE REVIEW

**Comment by hillelcoren** [comment]
Thanks for creating the PR, are you able to recreate it against the develop branch? Some change may hopefully not be needed.

**Comment by hillelcoren** [comment]
Ah... wait, develop branch is only for v2. Hmm, I think I'll create a review for the changes.

**Comment by hillelcoren** [comment]
For now we can only accept PRs on the legacy branch, we'll update the readme to make this clearer.

**Comment by viveky259259** [comment]
E

> Ah... wait, develop branch is only for v2. Hmm, I think I'll create a review for the changes.

This branch shows this error

```
invoiceninja_flutter depends on local_auth ^0.5.2+4 which depends on intl ^0.15.1, intl ^0.15.1 is required.
So, because invoiceninja_flutter depends on intl ^0.16.0, version solving failed.
```

basically we need to update every library's version to match with unversioned libraries. 
for example flutter_driver,flutter_localizations

**Comment by hillelcoren** [comment]
Are you seeing the same problem with the legacy branch?

**Pull request closed without merging**
